services:
  database:
    image: postgres:17.4-alpine
    container_name: rental_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rental_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rental_db_password}
      POSTGRES_DB: ${POSTGRES_DB:-rental_db}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
